#!/usr/bin/env python3
"""Build the whole muE4 line for both codes, with recording planes along it.

Differences from studies/mue4_g4bl/lattice.in, all deliberate:

  * Recording planes every metre or so, 22 of them, instead of the 4 detectors the
    real line carries. They sit only where the reference line is straight -- a plane
    inside one of the six turns has no well defined frame, and opalxruns.mue4.walk() refuses
    to place one there.
  * Nothing scrapes. The 12 iron objects become vacuum in G4beamline and the matching
    COLLIMATOR elements are left out of the OPALX line. The two codes remove different
    particles (OPALX does one inside/outside test, G4beamline scatters off iron), so
    with them in, the two phase space plots would differ partly because they hold
    different particles. With them out, every particle reaches every plane and what is
    left is the field maps and the tracking.
  * A Gaussian bunch written once and fed to both, with its sample mean subtracted
    exactly -- OPALX takes its reference orbit from the bunch mean, so a raw draw
    offsets every transverse number.

Run:  python make_full.py
"""
from __future__ import annotations
import math, re
from pathlib import Path
import numpy as np

from opalxruns.mue4 import CornerArc, Placement, Solid, parse_deck, walk
from opalxruns.paths import G4BL_FILES

HERE = Path(__file__).resolve().parent
SRC = G4BL_FILES / "muE4" / "g4bl_input" / "mue4_WsxOn.g4bl"
MAPS = G4BL_FILES / "muE4" / "maps"
MM = 1.0e-3

MUON_MASS = 0.1056583755
P0 = 0.028
BG0 = P0 / MUON_MASS

N_PART = 10000
SIG = dict(x=10.0e-3, y=3.0e-3, xp=2.0e-3, yp=2.0e-3)   # m and rad
SEED = 20260922

# Recording planes, centreline z in mm. Only where the reference line is straight:
# the turns occupy 2578-3387, 7142-7866 and 11670-12394, and a plane inside one of
# them has no chord frame. 540, 1285, 1700 and 19250 are the positions of the real
# detectors in muE4, kept as landmarks.
PLANES = [300, 540, 800, 1285, 1700, 2300,
          3500, 4300, 5100, 5900, 6700,
          8000, 8900, 9800, 10700, 11500,
          12500, 13800, 15100, 16400, 17700, 19250]

ZSTOP_M = 19.40
DT = "1e-12"
MAXSTEP_MM = 0.1
MAXSTEPS = 4000000


def monitor_placements(arcs):
    """One Placement per recording plane, with a line number that puts it in the right
    straight section. walk() interleaves placements and turns by line number, so a plane
    has to sort after every turn upstream of it and before every turn downstream."""
    det = Solid(kind="virtualdetector", name="PLANE", attrs={})
    out = []
    for z in PLANES:
        before = [a.line for a in arcs if a.cl_z <= z]
        line = (max(before) + 0.5) if before else 0.5
        out.append(Placement(index=-1, solid=det, name=f"PL{z:05d}", cl_z=float(z),
                             off_x=0.0, off_y=0.0, rotation="", current=None, line=line))
    return out


def write_lattice(placed):
    out = ["// lattice_full.in -- GENERATED by make_full.py, do not edit.",
           "//",
           "// The whole muE4 line: every field map at the position and rotation the",
           "// cornerarc walk gives it, plus 22 recording planes. No collimators -- nothing",
           "// scrapes in either code, so every particle reaches every plane.",
           "//",
           "// Names carry a number because OPALX sorts a line placed by absolute position",
           "// alphabetically, not by position.",
           ""]
    names = []
    for i, p in enumerate(placed, start=1):
        nm = f"E{i:02d}_{p.name}"
        pose = (f"X = {p.lab[0]*MM:.9f}, Y = {p.lab[1]*MM:.9f}, Z = {p.lab[2]*MM:.9f}, "
                f"THETA = {p.pose[0]:.9f}, PHI = {p.pose[1]:.9f}, PSI = {p.pose[2]:.9f}")
        note = f"  // centreline z = {p.cl_z:.4f} mm, frame {p.frame_deg:.2f} deg"
        if p.solid.kind == "fieldmap":
            f = Path(p.solid.attrs["file"]).name
            out += [f"{nm}: FIELDMAP, {pose},{note}",
                    f'    FMAPFN = "{MAPS / f}", SCALE = {p.current if p.current is not None else 1.0:.6e};', ""]
        else:
            out += [f"{nm}: MONITOR, {pose},{note}",
                    f'    DELETEONTRANSVERSEEXIT = FALSE, OUTFN = "{nm}";', ""]
        names.append(nm)
    out += [f"MUE4: LINE = ({', '.join(names)});", ""]
    (HERE / "lattice_full.in").write_text("\n".join(out))
    return names


def write_opalx():
    (HERE / "full.in").write_text(f"""/*  full.in -- the whole muE4 line in OPALX, paired with full.g4bl.

    {N_PART} muons from parts.txt, the same file G4beamline reads as beam.txt.
    Nothing scrapes: the line has no collimators, so every particle reaches every plane.

    DT = {DT} s. The single-magnet study showed 1e-11 s leaves about 30 um of the
    integrator's own error on one bend, which is larger than anything being compared,
    so the step here is ten times smaller. Over 19.4 m that is roughly 250 000 steps.

    GENERATED by make_full.py -- do not edit.
*/

OPTION, PSDUMPFREQ    = 100000;
OPTION, STATDUMPFREQ  = 10;        // reference orbit along the line
OPTION, BOUNDPDESTROY = 0;         // nothing may remove particles
OPTION, VERSION       = 10900;

Title, string="muE4 full line, field maps, no scraping";

REAL MUON_MASS = 0.1056583755;
REAL P0        = 0.028;

CALL, FILE = "lattice_full.in";

FS1: FIELDSOLVER, TYPE = NONE, NX = 8, NY = 8, NZ = 8,
     PARFFTX = true, PARFFTY = true, PARFFTZ = true,
     BCFFTX = open, BCFFTY = open, BCFFTZ = open,
     BBOXINCR = 1, GREENSF = INTEGRATED;

REAL n_particles = {N_PART};
Dist1: DISTRIBUTION, TYPE = FROMFILE, FNAME = "parts.txt", NPARTDIST = n_particles;
ES1: EMISSIONSOURCE, DISTRIBUTION = Dist1;
mySources: EMISSIONSOURCELIST = (ES1);

// CHARGE = 1 is mandatory: ParticleProperties maps MUON to -1 and Beam::execute only
// consults that table when the attribute is absent.
BEAM1: BEAM, PARTICLE = MUON, NALLOC = n_particles,
       BCHARGE = 1e-15, SOURCES = mySources, CHARGE = 1;

// ZSTOP is accumulated path length, directly comparable with G4beamline's centreline z.
TRACK, LINE = MUE4, BEAM = BEAM1,
       MAXSTEPS = {{{MAXSTEPS}}},
       DT = {{{DT}}},
       ZSTOP = {{{ZSTOP_M}}};
RUN, METHOD = "PARALLEL", FIELDSOLVER = FS1;
ENDTRACK;
Quit;
""")


def write_twin():
    """G4beamline: the real deck with the map paths fixed, nothing scraping, and one
    zntuple carrying all 22 planes."""
    out, opened = [], 0
    for raw in SRC.read_text().splitlines():
        line = raw
        s = line.strip()
        if s.startswith("fieldmap "):
            line = re.sub(r"file=\S+", lambda m: f"file={MAPS / Path(m.group(0)[5:]).name}", line)
        elif s.startswith("physics "):
            line = "physics QGSP_BERT disable=Decay spinTracking=0 doStochastics=0"
        elif s == "collective":
            line = "# collective -- dropped: there is no spacecharge command, so it did nothing"
        elif s.startswith("param maxstep"):
            line = (f"param maxStep={MAXSTEP_MM} deltaChord=0.001   # capital S; the deck's "
                    f"lower-case `maxstep` never took effect")
        elif s.startswith("beam "):
            line = "beam ascii filename=beam.txt"
        elif s.startswith("trackcuts"):
            line = "trackcuts keep=mu+ killSecondaries=1"
        elif s.startswith(("box ", "tubs ")) and "material=Fe" in line:
            line = line.replace("material=Fe", "material=Vacuum")
            line += "   # opened: OPALX and G4beamline do not scrape alike"
            opened += 1
        elif s.startswith(("virtualdetector ", "profile ", "zntuple ")):
            line = "# " + line
        elif s.startswith("place ") and re.match(r"place\s+(LEMSdet|EndOfSolenoidDet|virtDet)\b", s):
            line = "# " + line
        out.append(line)
    out += ["",
            "# All 22 recording planes, in centreline coordinates. Each writes Z<z>.txt.",
            f"zntuple z={','.join(str(z) for z in PLANES)} format=ascii coordinates=centerline",
            ""]
    (HERE / "full.g4bl").write_text("\n".join(out) + "\n")
    return opened


def write_beam():
    rng = np.random.default_rng(SEED)
    a = np.zeros((N_PART, 4))
    a[:, 0] = rng.normal(0.0, SIG["x"], N_PART)
    a[:, 1] = rng.normal(0.0, SIG["xp"], N_PART)
    a[:, 2] = rng.normal(0.0, SIG["y"], N_PART)
    a[:, 3] = rng.normal(0.0, SIG["yp"], N_PART)
    a -= a.mean(axis=0)          # exactly, not the population mean
    pz = BG0 / np.sqrt(1.0 + a[:, 1] ** 2 + a[:, 3] ** 2)
    px, py = a[:, 1] * pz, a[:, 3] * pz
    with open(HERE / "parts.txt", "w") as f:
        f.write(f"{N_PART}\nx y z px py pz\n")
        for i in range(N_PART):
            f.write(f"{a[i,0]:.12e} {a[i,2]:.12e} 0.0 {px[i]:.12e} {py[i]:.12e} {pz[i]:.12e}\n")
    with open(HERE / "beam.txt", "w") as f:
        f.write("#BLTrackFile written by make_full.py\n")
        f.write("#x y z Px Py Pz t PDGid EventID TrackID ParentID Weight\n")
        f.write("#mm mm mm MeV/c MeV/c MeV/c ns - - - - -\n")
        k = MUON_MASS * 1e3
        for i in range(N_PART):
            f.write(f"{a[i,0]*1e3:.12g} {a[i,2]*1e3:.12g} 0 {px[i]*k:.12g} {py[i]*k:.12g} "
                    f"{pz[i]*k:.12g} 0 -13 {i+1} 1 0 1\n")


def main():
    placements, arcs, solids = parse_deck(SRC)
    keep = [p for p in placements if p.solid.kind == "fieldmap"]
    combined = keep + monitor_placements(arcs)
    walk(combined, arcs)
    # walk() needs line order, because that is what tells it which turn a placement
    # sits after. The OPALX line needs beam order, which is centreline z. They are not
    # the same: every plane in one straight section shares a line number, so sorting by
    # line puts all of a section's planes before that section's magnets.
    placed = sorted(combined, key=lambda p: (p.cl_z, p.line))
    names = write_lattice(placed)
    write_opalx()
    opened = write_twin()
    write_beam()
    nmap = sum(1 for p in placed if p.solid.kind == "fieldmap")
    print(f"{len(placed)} elements: {nmap} field maps, {len(placed)-nmap} recording planes")
    print(f"opened {opened} iron objects in the G4beamline input")
    print(f"{N_PART} muons written to parts.txt and beam.txt")
    print(f"last plane at centreline z = {PLANES[-1]} mm, tracking to {ZSTOP_M} m")


if __name__ == "__main__":
    main()
