"""Writers for G4beamline's two field map formats, ``grid`` and ``cylinder``."""

from __future__ import annotations

import random
from pathlib import Path

MM = 1e-3                        # the map files are in millimetres


def write_grid_map(path: Path, field, xs_mm, ys_mm, zs_mm, norm_b=1.0,
                   current=1.0, comments=False, shuffle=False, columns=6,
                   scale=1.0, efield=None, norm_e=1.0, gradient=1.0,
                   escale=1.0) -> None:
    """Write the cartesian ``grid`` format: a header line naming the corner,
    the spacing and the point counts, then one row per point carrying its own
    coordinates and field.

    Passing ``efield`` writes the nine-column form and puts the electric field in the
    last three columns, in MV/m as G4beamline does. It is scaled by its own pair of
    header keys, ``normE`` and ``gradient``, exactly as the magnetic field is scaled by
    ``normB`` and ``current``.

    ``comments`` puts a block of '#' lines in front, which real maps from PSI
    have. ``shuffle`` puts the rows in a random order, which the reader has to
    cope with because it places rows by the coordinates they carry rather than
    by where they sit in the file. ``columns`` of 9 adds the zero Ex, Ey, Ez
    that G4beamline writes for some maps.
    """
    dx = xs_mm[1] - xs_mm[0]
    dy = ys_mm[1] - ys_mm[0]
    dz = zs_mm[1] - zs_mm[0]
    if efield is not None:
        columns = 9
    rows = []
    for x in xs_mm:
        for y in ys_mm:
            for z in zs_mm:                       # z varies fastest, as in real files
                bx, by, bz = field(x * MM, y * MM, z * MM)
                vals = [bx * scale, by * scale, bz * scale]
                if columns == 9:
                    if efield is None:
                        vals += [0.0, 0.0, 0.0]
                    else:
                        ex, ey, ez = efield(x * MM, y * MM, z * MM)
                        vals += [ex * escale, ey * escale, ez * escale]
                rows.append(f"{x:.4e} {y:.4e} {z:.4e} "
                            + " ".join(f"{v:.9e}" for v in vals))
    if shuffle:
        random.Random(20260921).shuffle(rows)
    out = []
    if comments:
        out += ["# generated by make_inputs.py for the OPALX G4beamline field map study",
                "# the same field as the plain map, with this comment block in front",
                "#"]
    param = f"param maxline=128 current={current:g} normB={norm_b:g}"
    if efield is not None:
        param += f" gradient={gradient:g} normE={norm_e:g}"
    out.append(param)
    out.append(f"grid X0={xs_mm[0]:.4f} Y0={ys_mm[0]:.4f} Z0={zs_mm[0]:.4f} "
               f"nX={len(xs_mm)} nY={len(ys_mm)} nZ={len(zs_mm)} "
               f"dX={dx:.4f} dY={dy:.4f} dZ={dz:.4f}")
    out.append("data")
    out += rows
    path.write_text("\n".join(out) + "\n")


def write_cylinder_map(path: Path, bz_br, rs_mm, zs_mm, norm_b=1.0, current=1.0,
                       mirror=False) -> None:
    """Write the axisymmetric ``cylinder`` format: a header line, then a 'Bz'
    block and a 'Br' block, each one row per z holding all nR values, with
    column 0 on the axis.

    ``mirror`` writes the field turned round the other way -- z reflected and
    Bz negated, Br left alone -- which is exactly what the reader's ZREVERSE
    does on load, so the two must track the same.
    """
    dr = rs_mm[1] - rs_mm[0]
    dz = zs_mm[1] - zs_mm[0]
    bz_rows, br_rows = [], []
    for z in zs_mm:
        zz = -z if mirror else z
        bzs, brs = [], []
        for r in rs_mm:
            bz, br = bz_br(r * MM, zz * MM)
            bzs.append(-bz if mirror else bz)
            brs.append(br)
        bz_rows.append(" ".join(f"{v:.9e}" for v in bzs))
        br_rows.append(" ".join(f"{v:.9e}" for v in brs))
    out = [f"param normB={norm_b:g} current={current:g}",
           f"cylinder X0=0.0000 Y0=0.0000 Z0={zs_mm[0]:.4f} "
           f"nZ={len(zs_mm)} nR={len(rs_mm)} dZ={dz:.4f} dR={dr:.4f}",
           "Bz"] + bz_rows + ["Br"] + br_rows
    path.write_text("\n".join(out) + "\n")
