#!/usr/bin/env python3
"""The whole muE4 line again, this time with spin tracking on in both codes.

Same 22 field maps, same 22 recording planes, same beam, nothing scraping — the
only difference from ../full is that the spin is carried and written out. The
lattice itself is unchanged, so it is copied rather than rebuilt.

The spin starts along the direction of travel. Real surface muons come out
polarized against their momentum; starting along it instead only flips the sign
of everything and makes the spin-momentum angle start at zero, which is the
quantity the anomaly shows up in.

Over muE4's 108 degrees of bending the spin should end up ahead of the momentum by

    G * gamma * theta = 1.16592061e-3 * 1.03452 * 1.8850 = 2.274 mrad

plus whatever the WSX solenoid adds, which turns the spin about the direction of
travel rather than in the bend plane.
"""
from __future__ import annotations
import shutil
from pathlib import Path
import numpy as np

HERE = Path(__file__).resolve().parent
FULL = HERE.parent / "full"
MUON_MASS, P0 = 0.1056583755, 0.028
BG0 = P0 / MUON_MASS
N_PART = 10000
SIG = dict(x=10.0e-3, y=3.0e-3, xp=2.0e-3, yp=2.0e-3)
SEED = 20260922
POL = (0.0, 0.0, 1.0)          # along the direction of travel
DT, MAXSTEP = "1e-12", 0.1
ZSTOP, MAXSTEPS = 19.40, 4000000
PLANES = [300, 540, 800, 1285, 1700, 2300, 3500, 4300, 5100, 5900, 6700,
          8000, 8900, 9800, 10700, 11500, 12500, 13800, 15100, 16400, 17700, 19250]


def beam_files():
    rng = np.random.default_rng(SEED)
    a = np.zeros((N_PART, 4))
    a[:, 0] = rng.normal(0.0, SIG["x"], N_PART)
    a[:, 1] = rng.normal(0.0, SIG["xp"], N_PART)
    a[:, 2] = rng.normal(0.0, SIG["y"], N_PART)
    a[:, 3] = rng.normal(0.0, SIG["yp"], N_PART)
    a -= a.mean(axis=0)
    pz = BG0 / np.sqrt(1.0 + a[:, 1] ** 2 + a[:, 3] ** 2)
    px, py = a[:, 1] * pz, a[:, 3] * pz
    with open(HERE / "parts.txt", "w") as f:
        f.write(f"{N_PART}\nx y z px py pz\n")
        for i in range(N_PART):
            f.write(f"{a[i,0]:.12e} {a[i,2]:.12e} 0.0 "
                    f"{px[i]:.12e} {py[i]:.12e} {pz[i]:.12e}\n")
    # 28 columns, which is the only form G4beamline reads spin from. It decides
    # by counting columns on the first data row, not by the header line.
    k = MUON_MASS * 1e3
    with open(HERE / "beam.txt", "w") as f:
        f.write("#BLTrackFile2 muE4 full line with spin\n")
        f.write("#x y z Px Py Pz t PDGid EventID TrackID ParentID Weight Bx By Bz "
                "Ex Ey Ez ProperTime PathLength PolX PolY PolZ InitX InitY InitZ "
                "InitT InitKE\n")
        f.write("#mm mm mm MeV/c MeV/c MeV/c ns - - - - - T T T MV/m MV/m MV/m ns mm "
                "- - - mm mm mm ns MeV\n")
        for i in range(N_PART):
            f.write(f"{a[i,0]*1e3:.12g} {a[i,2]*1e3:.12g} 0 {px[i]*k:.12g} "
                    f"{py[i]*k:.12g} {pz[i]*k:.12g} 0 -13 {i+1} 1 0 1 "
                    f"0 0 0 0 0 0 0 0 {POL[0]:.9g} {POL[1]:.9g} {POL[2]:.9g} "
                    f"{a[i,0]*1e3:.12g} {a[i,2]*1e3:.12g} 0 0 0\n")


def main():
    shutil.copy(FULL / "lattice_full.in", HERE / "lattice_full.in")
    beam_files()

    (HERE / "full_spin.in").write_text(f"""/*  full_spin.in -- the whole muE4 line with spin, paired with full_spin.g4bl.

    The same lattice, beam and step size as ../full, with one line added: the
    POLARIZATION attribute on the BEAM. Setting it at all is what makes OPALX
    carry a spin per particle and integrate Thomas-BMT; leaving it out turns spin
    tracking off entirely.

    FROMFILE ignores any spin in parts.txt, so every particle starts at the one
    vector below. The G4beamline beam file therefore carries the same vector on
    every row, or the two codes would not be given the same beam.

    GENERATED by make_full_spin.py -- do not edit.
*/

OPTION, PSDUMPFREQ    = 100000;
OPTION, STATDUMPFREQ  = 10;        // mean_polx/poly/polz/mean_pol_mag along the line
OPTION, BOUNDPDESTROY = 0;
OPTION, VERSION       = 10900;

Title, string="muE4 full line, field maps, spin";

REAL MUON_MASS = 0.1056583755;
REAL P0        = 0.028;

CALL, FILE = "lattice_full.in";

FS1: FIELDSOLVER, TYPE = NONE, NX = 8, NY = 8, NZ = 8,
     PARFFTX = true, PARFFTY = true, PARFFTZ = true,
     BCFFTX = open, BCFFTY = open, BCFFTZ = open,
     BBOXINCR = 1, GREENSF = INTEGRATED;

REAL n_particles = {N_PART};
Dist1: DISTRIBUTION, TYPE = FROMFILE, FNAME = "parts.txt", NPARTDIST = n_particles;
ES1: EMISSIONSOURCE, DISTRIBUTION = Dist1;
mySources: EMISSIONSOURCELIST = (ES1);

BEAM1: BEAM, PARTICLE = MUON, NALLOC = n_particles,
       BCHARGE = 1e-15, SOURCES = mySources, CHARGE = 1,
       POLARIZATION = {{{POL[0]}, {POL[1]}, {POL[2]}}};

TRACK, LINE = MUE4, BEAM = BEAM1,
       MAXSTEPS = {{{MAXSTEPS}}},
       DT = {{{DT}}},
       ZSTOP = {{{ZSTOP}}};
RUN, METHOD = "PARALLEL", FIELDSOLVER = FS1;
ENDTRACK;
Quit;
""")

    src = (FULL / "full.g4bl").read_text().splitlines()
    out = []
    for line in src:
        s = line.strip()
        if s.startswith("physics "):
            line = ("physics QGSP_BERT disable=Decay doStochastics=0 spinTracking=1"
                    "   # spinTracking=1 switches on Geant4's Thomas-BMT integration")
        elif s.startswith("beam "):
            line = "beam ascii filename=beam.txt"
        elif s.startswith("zntuple "):
            # asciiExtended is the 28-column text output carrying PolX PolY PolZ.
            # Plain `Extended` would resolve to ROOT in this build.
            line = (f"zntuple z={','.join(str(z) for z in PLANES)} "
                    f"format=asciiExtended coordinates=centerline")
        out.append(line)
    (HERE / "full_spin.g4bl").write_text("\n".join(out) + "\n")

    gamma = float(np.sqrt(1.0 + BG0 ** 2))
    theta = np.radians(108.0)
    print(f"{N_PART} muons, spin along the direction of travel {POL}")
    print(f"gamma = {gamma:.6f}, total bend {np.degrees(theta):.0f} deg = {theta:.4f} rad")
    print(f"expected spin ahead of momentum from the bends: "
          f"{1.16592061e-3*gamma*theta*1e3:.4f} mrad")
    print("wrote full_spin.in, full_spin.g4bl, parts.txt, beam.txt, lattice_full.in")


if __name__ == "__main__":
    main()
