#!/usr/bin/env python3
"""Write the OPALX input for the muE4 strong scaling runs on daint (GH200).

Starts from the full/ setup (../full/lattice_full.in, ../full/parts.txt) and changes
only what matters for timing:

  * The 22 MONITOR planes are left out. With N_PART particles each plane would write
    every particle to an .h5 file, which is gigabytes per run and mostly measures the
    file system.
  * FMAPFN points to maps/<file>, relative to the run folder. submit.sh links maps/
    into every run folder, so the input does not depend on where the maps sit.
  * N_PART particles: parts.txt from full/ repeated N_PART / 10000 times (make_beam.sh
    writes the file on daint). Without space charge the copies do not interact, so
    every particle costs the same work as in full/.
  * DT = 1e-11 s instead of 1e-12 s: about 25 000 steps instead of 250 000. The full/
    header says this leaves about 30 um of integrator error, which does not matter for
    timing.
  * No phase space dumps, statistics every 1000 steps.

Run:  python make_scaling.py
"""
from __future__ import annotations
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
FULL = HERE.parent / "full"

N_BASE = 10000                  # particles in ../full/parts.txt
N_PART = 16_000_000             # 2e6 per GPU at 8 GPUs
BEAM_FILE = f"parts_{N_PART // 1_000_000}M.txt"
DT = "1e-11"
ZSTOP_M = 19.40
MAXSTEPS = 4000000
STATDUMPFREQ = 1000


def write_lattice():
    """lattice_full.in without the MONITOR planes and with relative map paths."""
    blocks = (FULL / "lattice_full.in").read_text().split("\n\n")
    out = ["// lattice_scaling.in -- GENERATED by make_scaling.py from ../full/lattice_full.in,\n"
           "// do not edit.\n"
           "//\n"
           "// The field maps of the whole muE4 line, without the 22 MONITOR planes.\n"
           "// FMAPFN is relative to the run folder, which holds a link maps/."]
    names = []
    for b in blocks:
        m = re.match(r"(\w+):\s*(\w+)", b)
        if not m:
            continue                    # the header comment
        name, kind = m.groups()
        if kind in ("MONITOR", "LINE"):
            continue
        if kind != "FIELDMAP":
            raise SystemExit(f"unexpected element {name}: {kind}")
        b, n = re.subn(r'FMAPFN = "[^"]*/([^"/]+)"', r'FMAPFN = "maps/\1"', b)
        if n != 1:
            raise SystemExit(f"no FMAPFN in {name}")
        out.append(b.strip("\n"))
        names.append(name)
    out.append(f"MUE4: LINE = ({', '.join(names)});\n")
    (HERE / "lattice_scaling.in").write_text("\n\n".join(out))
    return names


def write_opalx():
    (HERE / "scaling.in").write_text(f"""/*  scaling.in -- the whole muE4 line, for strong scaling runs on daint.

    {N_PART} muons: ../full/parts.txt repeated {N_PART // N_BASE} times ({BEAM_FILE},
    written by make_beam.sh). Nothing scrapes, so the particle count stays the same
    over the whole run.

    DT = {DT} s, about 25 000 steps to ZSTOP. No MONITOR planes, no phase space dumps.

    GENERATED by make_scaling.py -- do not edit.
*/

OPTION, PSDUMPFREQ    = 0;         // no phase space dumps
OPTION, STATDUMPFREQ  = {STATDUMPFREQ};
OPTION, BOUNDPDESTROY = 0;         // nothing may remove particles
OPTION, VERSION       = 10900;

Title, string="muE4 full line, strong scaling";

REAL MUON_MASS = 0.1056583755;
REAL P0        = 0.028;

CALL, FILE = "lattice_scaling.in";

FS1: FIELDSOLVER, TYPE = NONE, NX = 8, NY = 8, NZ = 8,
     PARFFTX = true, PARFFTY = true, PARFFTZ = true,
     BCFFTX = open, BCFFTY = open, BCFFTZ = open,
     BBOXINCR = 1, GREENSF = INTEGRATED;

REAL n_particles = {N_PART};
Dist1: DISTRIBUTION, TYPE = FROMFILE, FNAME = "{BEAM_FILE}", NPARTDIST = n_particles;
ES1: EMISSIONSOURCE, DISTRIBUTION = Dist1;
mySources: EMISSIONSOURCELIST = (ES1);

// CHARGE = 1 is mandatory: ParticleProperties maps MUON to -1 and Beam::execute only
// consults that table when the attribute is absent.
BEAM1: BEAM, PARTICLE = MUON, NALLOC = n_particles,
       BCHARGE = 1e-15, SOURCES = mySources, CHARGE = 1;

TRACK, LINE = MUE4, BEAM = BEAM1,
       MAXSTEPS = {{{MAXSTEPS}}},
       DT = {{{DT}}},
       ZSTOP = {{{ZSTOP_M}}};
RUN, METHOD = "PARALLEL", FIELDSOLVER = FS1;
ENDTRACK;
Quit;
""")


def main():
    if N_PART % N_BASE:
        raise SystemExit(f"N_PART = {N_PART} is not a multiple of {N_BASE}")
    names = write_lattice()
    write_opalx()
    print(f"{len(names)} field maps in lattice_scaling.in")
    print(f"scaling.in: {N_PART} particles from {BEAM_FILE}, DT = {DT} s, ZSTOP = {ZSTOP_M} m")


if __name__ == "__main__":
    main()
