#!/usr/bin/env python3
"""The g-2 test: a uniform By bend at five momenta, in both codes.

In a field across the direction of travel the spin turns (1 + G*gamma) times
faster than the momentum, so the angle between spin and momentum grows as

    Delta = G * gamma * theta

Everything else in the Thomas-BMT equation is the same term that turns the
momentum; G*gamma is the only piece that is not. The bend angle is held at
0.5 rad while the momentum changes -- the field is scaled with the momentum to
do that -- so Delta depends only on gamma, and fitting the five points against
gamma recovers G in each code separately. That is a stronger statement than the
two codes agreeing once.
"""
from __future__ import annotations
from pathlib import Path
import numpy as np

from opalxruns.g4bl import write_grid_map

HERE = Path(__file__).resolve().parent

M = 0.1056583755          # muon rest mass [GeV]
G_OPALX = 1.16592061e-03
THETA = 0.5               # bend angle held fixed [rad]
L = 1.0                   # length of field [m]
MOMENTA = [0.028, 0.100, 0.300, 1.000, 3.094]   # GeV/c
DT = {0.028: "2.5e-13", 0.100: "2.5e-13", 0.300: "1e-13",
      1.000: "1e-13", 3.094: "1e-13"}
MAXSTEP = 0.05            # mm, G4beamline


def case_name(p):
    return f"by_p{int(round(p*1000)):04d}"


def main():
    print(f"{'case':>12} {'p [GeV/c]':>10} {'gamma':>9} {'B [T]':>9} "
          f"{'spin-momentum angle':>20}")
    rows = []
    for p in MOMENTA:
        d = HERE / case_name(p)
        d.mkdir(exist_ok=True)
        brho = p / 0.299792458
        B = brho * THETA / L
        bg = p / M
        gamma = float(np.sqrt(1.0 + bg * bg))
        expect = G_OPALX * gamma * THETA
        print(f"{case_name(p):>12} {p:10.3f} {gamma:9.4f} {B:9.4f} "
              f"{expect*1e3:17.4f} mrad")

        # the map: uniform By over 1 m. Wide in x, because the orbit bends by
        # 0.5 rad and swings a quarter of a metre sideways.
        xs = np.arange(-400.0, 400.1, 20.0)
        ys = np.arange(-60.0, 60.1, 20.0)
        zs = np.arange(-500.0, 500.1, 10.0)
        write_grid_map(d / "by.g4blmap", lambda x, y, z: (0.0, B, 0.0), xs, ys, zs)

        # one particle on the reference path, spin along the direction of travel
        pz_bg = bg
        (d / "parts.txt").write_text(
            "1\nx y z px py pz\n0.0 0.0 0.0 0.0 0.0 %.12e\n" % pz_bg)
        pz_mev = p * 1e3
        (d / "beam.txt").write_text(
            "#BLTrackFile2 %s\n" % case_name(p)
            + "#x y z Px Py Pz t PDGid EventID TrackID ParentID Weight Bx By Bz "
              "Ex Ey Ez ProperTime PathLength PolX PolY PolZ InitX InitY InitZ "
              "InitT InitKE\n"
            + "#mm mm mm MeV/c MeV/c MeV/c ns - - - - - T T T MV/m MV/m MV/m ns mm "
              "- - - mm mm mm ns MeV\n"
            + f"0 0 0 0 0 {pz_mev:.9g} 0 -13 1 1 0 1 0 0 0 0 0 0 0 0 "
              f"0 0 1 0 0 0 0 0\n")

        (d / f"{case_name(p)}.in").write_text(f"""/*  {case_name(p)}.in -- the g-2 test at p = {p} GeV/c.

    One metre of uniform By = {B:.9f} T, which bends a {p*1e3:.0f} MeV/c muon by
    {THETA} rad. The spin starts along the direction of travel, at (0, 0, 1).

    The spin turns (1 + G*gamma) times faster than the momentum, so after the bend
    the angle between them is

        G * gamma * theta = {expect:.6e} rad = {expect*1e3:.4f} mrad

    with gamma = {gamma:.6f}. The field is scaled with the momentum so the bend
    angle stays at {THETA} rad across the whole scan: then this angle depends only
    on gamma, and the five cases together measure G.

    GENERATED by make_scan.py -- do not edit.
*/

OPTION, PSDUMPFREQ    = 100000;
OPTION, STATDUMPFREQ  = 10;
OPTION, BOUNDPDESTROY = 0;
OPTION, VERSION       = 10900;

Title, string="spin_g4bl / {case_name(p)}";

REAL MUON_MASS = 0.1056583755;
REAL P0        = {p};

E01_MON_IN : MONITOR, X = 0.0, Y = 0.0, Z = 0.050,
             THETA = 0.0, PHI = 0.0, PSI = 0.0,
             DELETEONTRANSVERSEEXIT = FALSE, OUTFN = "MON_IN";

E02_BY     : FIELDMAP, X = 0.0, Y = 0.0, Z = 0.600,
             THETA = 0.0, PHI = 0.0, PSI = 0.0,
             FMAPFN = "by.g4blmap", SCALE = 1.0;

E03_MON_OUT: MONITOR, X = 0.0, Y = 0.0, Z = 1.200,
             THETA = 0.0, PHI = 0.0, PSI = 0.0,
             DELETEONTRANSVERSEEXIT = FALSE, OUTFN = "MON_OUT";

BendLine : LINE = (E01_MON_IN, E02_BY, E03_MON_OUT);

FS1: FIELDSOLVER, TYPE = NONE, NX = 8, NY = 8, NZ = 8,
     PARFFTX = true, PARFFTY = true, PARFFTZ = true,
     BCFFTX = open, BCFFTY = open, BCFFTZ = open,
     BBOXINCR = 1, GREENSF = INTEGRATED;

REAL n_particles = 1;
Dist1: DISTRIBUTION, TYPE = FROMFILE, FNAME = "parts.txt", NPARTDIST = n_particles;
ES1: EMISSIONSOURCE, DISTRIBUTION = Dist1;
mySources: EMISSIONSOURCELIST = (ES1);

// Spin along the direction of travel. FROMFILE ignores any spin in parts.txt, so
// this one vector is what every particle starts with.
BEAM1: BEAM, PARTICLE = MUON, NALLOC = n_particles,
       BCHARGE = 1e-15, SOURCES = mySources, CHARGE = 1,
       POLARIZATION = {{0.0, 0.0, 1.0}};

TRACK, LINE = BendLine, BEAM = BEAM1,
       MAXSTEPS = {{20000000}},
       DT = {{{DT[p]}}},
       ZSTOP = {{1.40}};
RUN, METHOD = "PARALLEL", FIELDSOLVER = FS1;
ENDTRACK;
Quit;
""")

        (d / f"{case_name(p)}.g4bl").write_text(f"""# {case_name(p)}.g4bl -- the g-2 test at p = {p} GeV/c.
#
# The same uniform By map OPALX reads. spinTracking=1 switches on Geant4's
# Thomas-BMT integration; decay is off, which also keeps spinTracking from
# swapping in the radiative decay channels.
#
# format=asciiExtended is the 28-column output carrying PolX PolY PolZ as text.
#
# GENERATED by make_scan.py -- do not edit.

physics QGSP_BERT disable=Decay doStochastics=0 spinTracking=1

param worldMaterial=Vacuum
param maxStep={MAXSTEP} deltaChord=0.0001

start x=0 y=0 z=0 initialZ=0 radiusCut=2000
reference particle=mu+ referenceMomentum={p*1e3:.6g}
trackcuts keep=mu+ killSecondaries=1

beam ascii filename=beam.txt

box WORLDBOX height=800 width=3000 length=2000 material=Vacuum
place WORLDBOX z=700 x=200

fieldmap BY file=by.g4blmap
place BY z=600 current=1.

zntuple z=50,1200 format=asciiExtended coordinates=centerline
""")
        rows.append(dict(name=case_name(p), p=p, gamma=gamma, B=B, expect=expect,
                         dt=DT[p], maxstep=MAXSTEP))
    import json
    (HERE / "scan.json").write_text(json.dumps(rows, indent=1))
    print(f"\nwrote {len(rows)} cases and scan.json")


if __name__ == "__main__":
    main()
